server:
  port: 8081
spring:
  application:
    name: my-app
  datasource:
    url: jdbc:mariadb://localhost:3307/hr
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    