server:
  port: 8081
jwt:
  secret: secretkey123
spring:
  application:
    name: my-app
  datasource:
    url: jdbc:mariadb://localhost:3308/hr
    username: root
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    