server:
  port: 8081
jwt:
  secret: secretkey123
spring:
  application:
    name: app
  datasource:
    url: jdbc:mariadb://localhost:3306/random2
    username: root
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    